### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by kasamizy** [thermocycle/Thermocycle-library#40]
How to cite the Thermocycle library in my own scientific research paper when I build a model by this library?

**Comment by squoilin** [comment]
Quoilin, S., Desideri, A., Wronski, J., Bell, I., & Lemort, V. (2014). ThermoCycle: A Modelica library for the simulation of thermodynamic systems. Proceedings of the 10th International Modelica Conference 2014.

**Comment by kasamizy** [comment]
Thank Dr. Squoilin for your kindly reply. I have learned a lot from your research.
Best wishes!
