### ISSUE TITLE
Installing thermocycle library on dymola

### ISSUE THREAD

**Issue by Shalom6624** [thermocycle/Thermocycle-library#50]
Hello,

Pls I am new to modelica. Just started working with dymola. Pls can anyone help me with instructions on how I can install the thermocycle library on dymola. I believe it can be installed on dymola but not sure how to do that. Thanks

**Comment by Shalom6624** [comment]
Figured it out. Thanks

**Comment by MagedBona** [comment]
Hello Shalom,
Can you share with me your experience or any installation guide, I try to work with the thermocycle library on Dymola but didn't succussed. 
Thanks
